var palette = (() => {

	// Colors courtesy of : https://htmlcolorcodes.com/color-names/
	// --
	// IMPORTANT: the first swatch key will be "1" so that "0" can represent transparent.
	var key = 0;
	var swatches = [
		{ name: "IndianRed",            hex: "#cd5c5c", key: ++key },
		{ name: "LightCoral",           hex: "#f08080", key: ++key },
		{ name: "Salmon",               hex: "#fa8072", key: ++key },
		{ name: "DarkSalmon",           hex: "#e9967a", key: ++key },
		{ name: "LightSalmon",          hex: "#ffa07a", key: ++key },
		{ name: "Crimson",              hex: "#dc143c", key: ++key },
		{ name: "Red",                  hex: "#ff0000", key: ++key },
		{ name: "FireBrick",            hex: "#b22222", key: ++key },
		{ name: "DarkRed",              hex: "#8b0000", key: ++key },
		{ name: "Pink",                 hex: "#ffc0cb", key: ++key },
		{ name: "LightPink",            hex: "#ffb6c1", key: ++key },
		{ name: "HotPink",              hex: "#ff69b4", key: ++key },
		{ name: "DeepPink",             hex: "#ff1493", key: ++key },
		{ name: "MediumVioletRed",      hex: "#c71585", key: ++key },
		{ name: "PaleVioletRed",        hex: "#db7093", key: ++key },
		{ name: "LightSalmon",          hex: "#ffa07a", key: ++key },
		{ name: "Coral",                hex: "#ff7f50", key: ++key },
		{ name: "Tomato",               hex: "#ff6347", key: ++key },
		{ name: "OrangeRed",            hex: "#ff4500", key: ++key },
		{ name: "DarkOrange",           hex: "#ff8c00", key: ++key },
		{ name: "Orange",               hex: "#ffa500", key: ++key },
		{ name: "Gold",                 hex: "#ffd700", key: ++key },
		{ name: "Yellow",               hex: "#ffff00", key: ++key },
		{ name: "LightYellow",          hex: "#ffffe0", key: ++key },
		{ name: "LemonChiffon",         hex: "#fffacd", key: ++key },
		{ name: "LightGoldenrodYellow", hex: "#fafad2", key: ++key },
		{ name: "PapayaWhip",           hex: "#ffefd5", key: ++key },
		{ name: "Moccasin",             hex: "#ffe4b5", key: ++key },
		{ name: "PeachPuff",            hex: "#ffdab9", key: ++key },
		{ name: "PaleGoldenrod",        hex: "#eee8aa", key: ++key },
		{ name: "Khaki",                hex: "#f0e68c", key: ++key },
		{ name: "DarkKhaki",            hex: "#bdb76b", key: ++key },
		{ name: "Lavender",             hex: "#e6e6fa", key: ++key },
		{ name: "Thistle",              hex: "#d8bfd8", key: ++key },
		{ name: "Plum",                 hex: "#dda0dd", key: ++key },
		{ name: "Violet",               hex: "#ee82ee", key: ++key },
		{ name: "Orchid",               hex: "#da70d6", key: ++key },
		{ name: "Fuchsia",              hex: "#ff00ff", key: ++key },
		{ name: "Magenta",              hex: "#ff00ff", key: ++key },
		{ name: "MediumOrchid",         hex: "#ba55d3", key: ++key },
		{ name: "MediumPurple",         hex: "#9370db", key: ++key },
		{ name: "RebeccaPurple",        hex: "#663399", key: ++key },
		{ name: "BlueViolet",           hex: "#8a2be2", key: ++key },
		{ name: "DarkViolet",           hex: "#9400d3", key: ++key },
		{ name: "DarkOrchid",           hex: "#9932cc", key: ++key },
		{ name: "DarkMagenta",          hex: "#8b008b", key: ++key },
		{ name: "Purple",               hex: "#800080", key: ++key },
		{ name: "Indigo",               hex: "#4b0082", key: ++key },
		{ name: "SlateBlue",            hex: "#6a5acd", key: ++key },
		{ name: "DarkSlateBlue",        hex: "#483d8b", key: ++key },
		{ name: "MediumSlateBlue",      hex: "#7b68ee", key: ++key },
		{ name: "GreenYellow",          hex: "#adff2f", key: ++key },
		{ name: "Chartreuse",           hex: "#7fff00", key: ++key },
		{ name: "LawnGreen",            hex: "#7cfc00", key: ++key },
		{ name: "Lime",                 hex: "#00ff00", key: ++key },
		{ name: "LimeGreen",            hex: "#32cd32", key: ++key },
		{ name: "PaleGreen",            hex: "#98fb98", key: ++key },
		{ name: "LightGreen",           hex: "#90ee90", key: ++key },
		{ name: "MediumSpringGreen",    hex: "#00fa9a", key: ++key },
		{ name: "SpringGreen",          hex: "#00ff7f", key: ++key },
		{ name: "MediumSeaGreen",       hex: "#3cb371", key: ++key },
		{ name: "SeaGreen",             hex: "#2e8b57", key: ++key },
		{ name: "ForestGreen",          hex: "#228b22", key: ++key },
		{ name: "Green",                hex: "#008000", key: ++key },
		{ name: "DarkGreen",            hex: "#006400", key: ++key },
		{ name: "YellowGreen",          hex: "#9acd32", key: ++key },
		{ name: "OliveDrab",            hex: "#6b8e23", key: ++key },
		{ name: "Olive",                hex: "#808000", key: ++key },
		{ name: "DarkOliveGreen",       hex: "#556b2f", key: ++key },
		{ name: "MediumAquamarine",     hex: "#66cdaa", key: ++key },
		{ name: "DarkSeaGreen",         hex: "#8fbc8b", key: ++key },
		{ name: "LightSeaGreen",        hex: "#20b2aa", key: ++key },
		{ name: "DarkCyan",             hex: "#008b8b", key: ++key },
		{ name: "Teal",                 hex: "#008080", key: ++key },
		{ name: "Aqua",                 hex: "#00ffff", key: ++key },
		{ name: "Cyan",                 hex: "#00ffff", key: ++key },
		{ name: "LightCyan",            hex: "#e0ffff", key: ++key },
		{ name: "PaleTurquoise",        hex: "#afeeee", key: ++key },
		{ name: "Aquamarine",           hex: "#7fffd4", key: ++key },
		{ name: "Turquoise",            hex: "#40e0d0", key: ++key },
		{ name: "MediumTurquoise",      hex: "#48d1cc", key: ++key },
		{ name: "DarkTurquoise",        hex: "#00ced1", key: ++key },
		{ name: "CadetBlue",            hex: "#5f9ea0", key: ++key },
		{ name: "SteelBlue",            hex: "#4682b4", key: ++key },
		{ name: "LightSteelBlue",       hex: "#b0c4de", key: ++key },
		{ name: "PowderBlue",           hex: "#b0e0e6", key: ++key },
		{ name: "LightBlue",            hex: "#add8e6", key: ++key },
		{ name: "SkyBlue",              hex: "#87ceeb", key: ++key },
		{ name: "LightSkyBlue",         hex: "#87cefa", key: ++key },
		{ name: "DeepSkyBlue",          hex: "#00bfff", key: ++key },
		{ name: "DodgerBlue",           hex: "#1e90ff", key: ++key },
		{ name: "CornflowerBlue",       hex: "#6495ed", key: ++key },
		{ name: "MediumSlateBlue",      hex: "#7b68ee", key: ++key },
		{ name: "RoyalBlue",            hex: "#4169e1", key: ++key },
		{ name: "Blue",                 hex: "#0000ff", key: ++key },
		{ name: "MediumBlue",           hex: "#0000cd", key: ++key },
		{ name: "DarkBlue",             hex: "#00008b", key: ++key },
		{ name: "Navy",                 hex: "#000080", key: ++key },
		{ name: "MidnightBlue",         hex: "#191970", key: ++key },
		{ name: "Cornsilk",             hex: "#fff8dc", key: ++key },
		{ name: "BlanchedAlmond",       hex: "#ffebcd", key: ++key },
		{ name: "Bisque",               hex: "#ffe4c4", key: ++key },
		{ name: "NavajoWhite",          hex: "#ffdead", key: ++key },
		{ name: "Wheat",                hex: "#f5deb3", key: ++key },
		{ name: "BurlyWood",            hex: "#deb887", key: ++key },
		{ name: "Tan",                  hex: "#d2b48c", key: ++key },
		{ name: "RosyBrown",            hex: "#bc8f8f", key: ++key },
		{ name: "SandyBrown",           hex: "#f4a460", key: ++key },
		{ name: "Goldenrod",            hex: "#daa520", key: ++key },
		{ name: "DarkGoldenrod",        hex: "#b8860b", key: ++key },
		{ name: "Peru",                 hex: "#cd853f", key: ++key },
		{ name: "Chocolate",            hex: "#d2691e", key: ++key },
		{ name: "SaddleBrown",          hex: "#8b4513", key: ++key },
		{ name: "Sienna",               hex: "#a0522d", key: ++key },
		{ name: "Brown",                hex: "#a52a2a", key: ++key },
		{ name: "Maroon",               hex: "#800000", key: ++key },
		{ name: "Snow",                 hex: "#fffafa", key: ++key },
		{ name: "HoneyDew",             hex: "#f0fff0", key: ++key },
		{ name: "MintCream",            hex: "#f5fffa", key: ++key },
		{ name: "Azure",                hex: "#f0ffff", key: ++key },
		{ name: "AliceBlue",            hex: "#f0f8ff", key: ++key },
		{ name: "GhostWhite",           hex: "#f8f8ff", key: ++key },
		{ name: "WhiteSmoke",           hex: "#f5f5f5", key: ++key },
		{ name: "SeaShell",             hex: "#fff5ee", key: ++key },
		{ name: "Beige",                hex: "#f5f5dc", key: ++key },
		{ name: "OldLace",              hex: "#fdf5e6", key: ++key },
		{ name: "FloralWhite",          hex: "#fffaf0", key: ++key },
		{ name: "Ivory",                hex: "#fffff0", key: ++key },
		{ name: "AntiqueWhite",         hex: "#faebd7", key: ++key },
		{ name: "Linen",                hex: "#faf0e6", key: ++key },
		{ name: "LavenderBlush",        hex: "#fff0f5", key: ++key },
		{ name: "MistyRose",            hex: "#ffe4e1", key: ++key },
		{ name: "Gainsboro",            hex: "#dcdcdc", key: ++key },
		{ name: "LightGray",            hex: "#d3d3d3", key: ++key },
		{ name: "Silver",               hex: "#c0c0c0", key: ++key },
		{ name: "DarkGray",             hex: "#a9a9a9", key: ++key },
		{ name: "Gray",                 hex: "#808080", key: ++key },
		{ name: "DimGray",              hex: "#696969", key: ++key },
		{ name: "LightSlateGray",       hex: "#778899", key: ++key },
		{ name: "SlateGray",            hex: "#708090", key: ++key },
		{ name: "DarkSlateGray",        hex: "#2f4f4f", key: ++key },
		{ name: "Black",                hex: "#000000", key: ++key },
		{ name: "White",                hex: "#ffffff", key: ++key }
	];

	return {
		swatches,
		byName: indexBy( "name" ),
		byHex: indexBy( "hex" ),
		byKey: indexBy( "key" )
	};

	// ------------------------------------------------------------------------------- //
	// ------------------------------------------------------------------------------- //

	/**
	* I index the swatches collection by the given property.
	*/
	function indexBy( property ) {

		var index = {};

		for ( var swatch of swatches ) {

			index[ swatch[ property ] ] = swatch;

		}

		return index;

	}

})();
